version: '3'

services:
  api-gateway:
    build: ./api-gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app
  coupon-service:
    build: ./coupon-service
    restart: always
    hostname: coupon-service
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - rabbitmq
  mailer-service:
    build: ./mailer-service
    restart: always
    hostname: mailer-service
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - rabbitmq
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=admin123
    networks:
      - app
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

networks:
  app:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local